//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEventCalendar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_User
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string FullName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string Password { get; set; }
        public Nullable<short> PWReset { get; set; }
        public Nullable<short> AccessLevelID { get; set; }
        public Nullable<int> ScreenAccess { get; set; }
        public Nullable<short> Active { get; set; }
        public string Department { get; set; }
        public Nullable<int> SubDepartment { get; set; }
        public string WorkCenter { get; set; }
        public string emailAddress { get; set; }
        public string Hagen_ID { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "This field is required")]
        public string EmployeeNo { get; set; }
        public string EmployeePhoto { get; set; }
        public string Manager { get; set; }
        public string Position { get; set; }
        public string PDFFolder { get; set; }
        public Nullable<short> PATDockAlert { get; set; }
        public Nullable<short> PATReturnAlert { get; set; }
        public Nullable<short> PATVerifiedAlert { get; set; }
        public Nullable<short> PATCloseOutAlert { get; set; }
        public Nullable<bool> Management { get; set; }
        public Nullable<short> Directory { get; set; }
        public string PhoneDirect { get; set; }
        public string PhoneCell { get; set; }
        public string PhoneFax { get; set; }
        public string PhoneTollFree { get; set; }
        public string PhoneMain { get; set; }
        public string PhoneExt { get; set; }
        public string SMSAddress { get; set; }
        public string AcctFax { get; set; }
        public string HandworkPhone { get; set; }
        public string Handworkext { get; set; }
        public string HRFax { get; set; }
        public string CCFax { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string St { get; set; }
        public string Zip { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> UsePhoto { get; set; }
        public Nullable<short> Internal { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> SecurityGroup { get; set; }
        public Nullable<int> igroup { get; set; }
        public Nullable<bool> DirectoryAdmin { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
